# Configuration for markdownlint-cli2 with sentences-per-line plugin
# This file can be referenced from remote lefthook configs

# Custom rules to load
customRules:
  - sentences-per-line

# Rule configuration
config:
  # Enable sentences-per-line rule for better Git diffs
  sentences-per-line: true

  # Standard markdownlint rules (customize as needed)
  default: true

  # Disable line length - sentences-per-line handles this better
  MD013: false

  # Allow inline HTML (common in many projects)
  MD033: false

  # First line doesn't have to be top-level heading
  MD041: false

# Files to lint (default patterns)
globs:
  - "**/*.md"
  - "**/*.markdown"

# Files and directories to ignore
ignores:
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.lefthook*/**"
